version: '3.7'

networks:
  idlr:
    name: idlr-network

services:
  # Orderer
  orderer.idlr.gov.ng:
    container_name: orderer.idlr.gov.ng
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./organizations/ordererOrganizations/idlr.gov.ng/orderers/orderer.idlr.gov.ng/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/idlr.gov.ng/orderers/orderer.idlr.gov.ng/tls/:/var/hyperledger/orderer/tls
      - orderer.idlr.gov.ng:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 9443:9443
    networks:
      - idlr

  # Government Peer
  peer0.government.idlr.gov.ng:
    container_name: peer0.government.idlr.gov.ng
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=idlr-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.government.idlr.gov.ng
      - CORE_PEER_ADDRESS=peer0.government.idlr.gov.ng:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.government.idlr.gov.ng:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.government.idlr.gov.ng:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.government.idlr.gov.ng:7051
      - CORE_PEER_LOCALMSPID=GovernmentMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/government.idlr.gov.ng/peers/peer0.government.idlr.gov.ng/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/government.idlr.gov.ng/peers/peer0.government.idlr.gov.ng/tls:/etc/hyperledger/fabric/tls
      - peer0.government.idlr.gov.ng:/var/hyperledger/production
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - idlr
    depends_on:
      - couchdb0

  # CouchDB for Government Peer
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - idlr

  # Bank Peer
  peer0.bank.idlr.gov.ng:
    container_name: peer0.bank.idlr.gov.ng
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=idlr-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.bank.idlr.gov.ng
      - CORE_PEER_ADDRESS=peer0.bank.idlr.gov.ng:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank.idlr.gov.ng:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank.idlr.gov.ng:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.idlr.gov.ng:8051
      - CORE_PEER_LOCALMSPID=BankMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9445
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/bank.idlr.gov.ng/peers/peer0.bank.idlr.gov.ng/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/bank.idlr.gov.ng/peers/peer0.bank.idlr.gov.ng/tls:/etc/hyperledger/fabric/tls
      - peer0.bank.idlr.gov.ng:/var/hyperledger/production
    ports:
      - 8051:8051
      - 9445:9445
    networks:
      - idlr
    depends_on:
      - couchdb1

  # CouchDB for Bank Peer
  couchdb1:
    container_name: couchdb1
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    networks:
      - idlr

  # Notary Peer
  peer0.notary.idlr.gov.ng:
    container_name: peer0.notary.idlr.gov.ng
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=idlr-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.notary.idlr.gov.ng
      - CORE_PEER_ADDRESS=peer0.notary.idlr.gov.ng:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.notary.idlr.gov.ng:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.notary.idlr.gov.ng:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.notary.idlr.gov.ng:9051
      - CORE_PEER_LOCALMSPID=NotaryMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9446
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/notary.idlr.gov.ng/peers/peer0.notary.idlr.gov.ng/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/notary.idlr.gov.ng/peers/peer0.notary.idlr.gov.ng/tls:/etc/hyperledger/fabric/tls
      - peer0.notary.idlr.gov.ng:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9446:9446
    networks:
      - idlr
    depends_on:
      - couchdb2

  # CouchDB for Notary Peer
  couchdb2:
    container_name: couchdb2
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7984:5984
    networks:
      - idlr

  # CLI
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.government.idlr.gov.ng:7051
      - CORE_PEER_LOCALMSPID=GovernmentMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government.idlr.gov.ng/peers/peer0.government.idlr.gov.ng/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government.idlr.gov.ng/peers/peer0.government.idlr.gov.ng/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government.idlr.gov.ng/peers/peer0.government.idlr.gov.ng/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government.idlr.gov.ng/users/Admin@government.idlr.gov.ng/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.government.idlr.gov.ng
      - peer0.bank.idlr.gov.ng
      - peer0.notary.idlr.gov.ng
    networks:
      - idlr

volumes:
  orderer.idlr.gov.ng:
  peer0.government.idlr.gov.ng:
  peer0.bank.idlr.gov.ng:
  peer0.notary.idlr.gov.ng:
