ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'tax_manager';--> statement-breakpoint
ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'tax_assessor';--> statement-breakpoint
ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'tax_reviewer';--> statement-breakpoint
CREATE TYPE "tax_assessment_status" AS ENUM ('draft', 'evidence_pending', 'under_review', 'issued', 'appealed', 'closed', 'withdrawn');--> statement-breakpoint
CREATE TYPE "tax_appeal_status" AS ENUM ('filed', 'under_review', 'upheld', 'adjusted', 'withdrawn');--> statement-breakpoint
CREATE TABLE "tax_assessment_cases" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "case_key" varchar(96) NOT NULL UNIQUE, "account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE, "parcel_id" integer NOT NULL REFERENCES "parcels"("id") ON DELETE RESTRICT, "tax_year" integer NOT NULL, "status" "tax_assessment_status" NOT NULL DEFAULT 'draft', "declared_basis_minor" bigint, "currency" varchar(3) NOT NULL DEFAULT 'USD', "assessed_amount_minor" bigint, "assessment_reference" varchar(160), "created_by" integer NOT NULL REFERENCES "users"("id"), "reviewed_by" integer REFERENCES "users"("id"), "reviewed_at" timestamptz, "issued_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), UNIQUE("account_id", "parcel_id", "tax_year"), CONSTRAINT "tax_year_reasonable" CHECK ("tax_year" BETWEEN 2000 AND 2200), CONSTRAINT "tax_amount_positive" CHECK ("assessed_amount_minor" IS NULL OR "assessed_amount_minor" >= 0));--> statement-breakpoint
CREATE TABLE "tax_assessment_evidence" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "evidence_key" varchar(96) NOT NULL UNIQUE, "case_id" bigint NOT NULL REFERENCES "tax_assessment_cases"("id") ON DELETE CASCADE, "kind" varchar(64) NOT NULL, "source_reference" varchar(160) NOT NULL, "description" text NOT NULL, "submitted_by" integer NOT NULL REFERENCES "users"("id"), "reviewed_by" integer REFERENCES "users"("id"), "reviewed_at" timestamptz, "accepted" boolean, "created_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "tax_assessment_appeals" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "appeal_key" varchar(96) NOT NULL UNIQUE, "case_id" bigint NOT NULL REFERENCES "tax_assessment_cases"("id") ON DELETE CASCADE, "status" "tax_appeal_status" NOT NULL DEFAULT 'filed', "grounds" text NOT NULL, "evidence_reference" varchar(160) NOT NULL, "filed_by" integer NOT NULL REFERENCES "users"("id"), "decided_by" integer REFERENCES "users"("id"), "decision_note" text, "decided_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "tax_payment_references" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "payment_key" varchar(96) NOT NULL UNIQUE, "case_id" bigint NOT NULL REFERENCES "tax_assessment_cases"("id") ON DELETE RESTRICT, "provider" varchar(32) NOT NULL, "provider_reference" varchar(160) NOT NULL, "amount_minor" bigint NOT NULL, "currency" varchar(3) NOT NULL, "verified_at" timestamptz, "verified_by" integer REFERENCES "users"("id"), "created_at" timestamptz NOT NULL DEFAULT now(), UNIQUE("provider", "provider_reference"), CONSTRAINT "tax_payment_amount_nonnegative" CHECK ("amount_minor" >= 0));--> statement-breakpoint
CREATE TABLE "tax_operation_events" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE, "case_key" varchar(96) NOT NULL, "event_type" varchar(64) NOT NULL, "actor_id" integer NOT NULL REFERENCES "users"("id"), "description" text NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE INDEX "tax_cases_account_status_idx" ON "tax_assessment_cases"("account_id", "status", "updated_at");--> statement-breakpoint
CREATE INDEX "tax_evidence_case_idx" ON "tax_assessment_evidence"("case_id", "created_at");--> statement-breakpoint
CREATE INDEX "tax_appeals_case_idx" ON "tax_assessment_appeals"("case_id", "status");--> statement-breakpoint
INSERT INTO "commercial_products" ("product_key", "name", "description", "monthly_price_minor", "currency", "included_seats", "included_units") VALUES ('valuation-tax-operations', 'Valuation and Property-Tax Operations', 'Human-reviewed assessment, evidence, appeal, and verified payment-reference workflows.', 250000, 'USD', 15, '{"monthly_assessment_cases":3000}'::jsonb) ON CONFLICT ("product_key") DO NOTHING;
