ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'acquisition_manager';--> statement-breakpoint
ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'acquisition_reviewer';--> statement-breakpoint
ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'exposure_manager';--> statement-breakpoint
ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'api_admin';--> statement-breakpoint
ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'planning_analyst';--> statement-breakpoint
ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'rural_manager';--> statement-breakpoint
ALTER TYPE "commercial_member_role" ADD VALUE IF NOT EXISTS 'service_provider_manager';--> statement-breakpoint
CREATE TYPE "portfolio_review_status" AS ENUM ('draft','open','under_review','approved','closed','withdrawn');--> statement-breakpoint
CREATE TYPE "provider_verification_status" AS ENUM ('pending','verified','rejected','suspended');--> statement-breakpoint
CREATE TYPE "service_request_status" AS ENUM ('submitted','accepted','in_progress','completed','cancelled','disputed');--> statement-breakpoint
CREATE TABLE "acquisition_datarooms" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE,"dataroom_key" varchar(96) NOT NULL UNIQUE,"name" varchar(200) NOT NULL,"purpose" varchar(160) NOT NULL,"status" "portfolio_review_status" NOT NULL DEFAULT 'draft',"created_by" integer NOT NULL REFERENCES "users"("id"),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "acquisition_due_diligence_items" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"item_key" varchar(96) NOT NULL UNIQUE,"dataroom_id" bigint NOT NULL REFERENCES "acquisition_datarooms"("id") ON DELETE CASCADE,"parcel_id" integer REFERENCES "parcels"("id") ON DELETE SET NULL,"category" varchar(64) NOT NULL,"source_reference" varchar(160) NOT NULL,"factual_summary" text NOT NULL,"status" "portfolio_review_status" NOT NULL DEFAULT 'open',"reviewed_by" integer REFERENCES "users"("id"),"reviewed_at" timestamptz,"created_by" integer NOT NULL REFERENCES "users"("id"),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "exposure_portfolios" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE,"portfolio_key" varchar(96) NOT NULL UNIQUE,"name" varchar(200) NOT NULL,"status" "portfolio_review_status" NOT NULL DEFAULT 'open',"created_by" integer NOT NULL REFERENCES "users"("id"),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "exposure_assets" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"portfolio_id" bigint NOT NULL REFERENCES "exposure_portfolios"("id") ON DELETE CASCADE,"asset_key" varchar(96) NOT NULL UNIQUE,"parcel_id" integer REFERENCES "parcels"("id") ON DELETE SET NULL,"label" varchar(200) NOT NULL,"latitude" double precision NOT NULL,"longitude" double precision NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "exposure_assets_lat" CHECK ("latitude" BETWEEN -90 AND 90),CONSTRAINT "exposure_assets_lon" CHECK ("longitude" BETWEEN -180 AND 180));--> statement-breakpoint
CREATE TABLE "exposure_snapshots" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"snapshot_key" varchar(96) NOT NULL UNIQUE,"portfolio_id" bigint NOT NULL REFERENCES "exposure_portfolios"("id") ON DELETE CASCADE,"context_layer" varchar(64) NOT NULL,"source_reference" varchar(160) NOT NULL,"observed_at" timestamptz NOT NULL,"summary" text NOT NULL,"human_review_note" text,"created_by" integer NOT NULL REFERENCES "users"("id"),"created_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "property_api_clients" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE,"client_key" varchar(96) NOT NULL UNIQUE,"name" varchar(160) NOT NULL,"purpose" varchar(400) NOT NULL,"scopes" jsonb NOT NULL,"key_hash" varchar(128) NOT NULL UNIQUE,"status" "portfolio_review_status" NOT NULL DEFAULT 'draft',"created_by" integer NOT NULL REFERENCES "users"("id"),"rotated_at" timestamptz,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "property_api_usage" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"client_id" bigint NOT NULL REFERENCES "property_api_clients"("id") ON DELETE CASCADE,"request_key" varchar(96) NOT NULL UNIQUE,"endpoint" varchar(160) NOT NULL,"scope" varchar(96) NOT NULL,"response_count" integer NOT NULL,"purpose_reference" varchar(160) NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "property_api_usage_count_nonnegative" CHECK ("response_count" >= 0));--> statement-breakpoint
CREATE TABLE "planning_aggregate_reports" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"report_key" varchar(96) NOT NULL UNIQUE,"account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE,"name" varchar(200) NOT NULL,"cohort_size" integer NOT NULL,"minimum_cohort" integer NOT NULL,"status" "portfolio_review_status" NOT NULL DEFAULT 'draft',"suppressed" boolean NOT NULL DEFAULT false,"summary" jsonb NOT NULL,"created_by" integer NOT NULL REFERENCES "users"("id"),"published_by" integer REFERENCES "users"("id"),"published_at" timestamptz,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "planning_cohort_nonnegative" CHECK ("cohort_size" >= 0 AND "minimum_cohort" > 0));--> statement-breakpoint
CREATE TABLE "rural_service_cases" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"case_key" varchar(96) NOT NULL UNIQUE,"account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE,"parcel_id" integer REFERENCES "parcels"("id") ON DELETE SET NULL,"program_type" varchar(96) NOT NULL,"status" "portfolio_review_status" NOT NULL DEFAULT 'draft',"consent_reference" varchar(160) NOT NULL,"service_reference" varchar(160) NOT NULL,"created_by" integer NOT NULL REFERENCES "users"("id"),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "service_providers" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"provider_key" varchar(96) NOT NULL UNIQUE,"account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE,"legal_name" varchar(255) NOT NULL,"service_categories" jsonb NOT NULL,"service_radius_km" integer NOT NULL,"verification_status" "provider_verification_status" NOT NULL DEFAULT 'pending',"verification_reference" varchar(160),"reviewed_by" integer REFERENCES "users"("id"),"reviewed_at" timestamptz,"created_by" integer NOT NULL REFERENCES "users"("id"),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "service_provider_radius" CHECK ("service_radius_km" BETWEEN 1 AND 1000));--> statement-breakpoint
CREATE TABLE "service_requests" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"request_key" varchar(96) NOT NULL UNIQUE,"account_id" bigint NOT NULL REFERENCES "commercial_accounts"("id") ON DELETE CASCADE,"provider_id" bigint REFERENCES "service_providers"("id") ON DELETE SET NULL,"parcel_id" integer REFERENCES "parcels"("id") ON DELETE SET NULL,"service_category" varchar(96) NOT NULL,"consent_reference" varchar(160) NOT NULL,"status" "service_request_status" NOT NULL DEFAULT 'submitted',"requester_reference" varchar(160) NOT NULL,"created_by" integer NOT NULL REFERENCES "users"("id"),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE TABLE "service_disputes" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"dispute_key" varchar(96) NOT NULL UNIQUE,"request_id" bigint NOT NULL REFERENCES "service_requests"("id") ON DELETE CASCADE,"grounds" text NOT NULL,"status" "portfolio_review_status" NOT NULL DEFAULT 'open',"resolution_note" text,"filed_by" integer NOT NULL REFERENCES "users"("id"),"reviewed_by" integer REFERENCES "users"("id"),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE INDEX "acquisition_dataroom_account_idx" ON "acquisition_datarooms"("account_id","status");--> statement-breakpoint
CREATE INDEX "exposure_portfolio_account_idx" ON "exposure_portfolios"("account_id","status");--> statement-breakpoint
CREATE INDEX "api_client_account_idx" ON "property_api_clients"("account_id","status");--> statement-breakpoint
CREATE INDEX "planning_report_account_idx" ON "planning_aggregate_reports"("account_id","status");--> statement-breakpoint
CREATE INDEX "rural_case_account_idx" ON "rural_service_cases"("account_id","status");--> statement-breakpoint
CREATE INDEX "service_request_account_idx" ON "service_requests"("account_id","status");--> statement-breakpoint
INSERT INTO "commercial_products" ("product_key","name","description","monthly_price_minor","currency","included_seats","included_units") VALUES
('acquisition-intelligence','Development and Acquisition Intelligence','Governed data rooms and human-reviewed due diligence workflows.',400000,'USD',20,'{"monthly_diligence_items":4000}'::jsonb),
('resilience-exposure-monitor','Resilience and Exposure Monitor','Attributed public-context portfolio snapshots with human review.',275000,'USD',20,'{"monthly_exposure_snapshots":10000}'::jsonb),
('property-data-api','Property Data and Integration API','Purpose-bound scope-controlled integration access.',350000,'USD',10,'{"monthly_api_requests":100000}'::jsonb),
('planning-analytics','Land Market and Planning Analytics','Privacy-suppressed aggregate planning reports.',225000,'USD',15,'{"monthly_aggregate_reports":500}'::jsonb),
('rural-agribusiness-hub','Rural Land and Agribusiness Service Hub','Consent-backed rural land service case workflows.',175000,'USD',25,'{"monthly_rural_cases":3000}'::jsonb),
('trusted-service-directory','Trusted Marketplace and Service Directory','Verified provider directory and consented service request workflows.',150000,'USD',25,'{"monthly_service_requests":5000}'::jsonb)
ON CONFLICT ("product_key") DO NOTHING;
