apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: idlr-pts-config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://jaeger:9411/api/v2/spans"
  metric:
    enabled: true
  features:
    - name: ActorStateTTL
      enabled: true
    - name: SchedulerHostAddress
      enabled: false
