// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/ledger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account types
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_ASSET       AccountType = 1 // Property escrow, user wallets
	AccountType_ACCOUNT_TYPE_LIABILITY   AccountType = 2 // Pending payments, obligations
	AccountType_ACCOUNT_TYPE_EQUITY      AccountType = 3 // Platform equity accounts
	AccountType_ACCOUNT_TYPE_REVENUE     AccountType = 4 // Transaction fees, service charges
	AccountType_ACCOUNT_TYPE_EXPENSE     AccountType = 5 // Operating expenses, gas fees
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_ASSET",
		2: "ACCOUNT_TYPE_LIABILITY",
		3: "ACCOUNT_TYPE_EQUITY",
		4: "ACCOUNT_TYPE_REVENUE",
		5: "ACCOUNT_TYPE_EXPENSE",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_ASSET":       1,
		"ACCOUNT_TYPE_LIABILITY":   2,
		"ACCOUNT_TYPE_EQUITY":      3,
		"ACCOUNT_TYPE_REVENUE":     4,
		"ACCOUNT_TYPE_EXPENSE":     5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ledger_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_ledger_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

// Transfer status
type TransferStatus int32

const (
	TransferStatus_TRANSFER_STATUS_UNSPECIFIED TransferStatus = 0
	TransferStatus_TRANSFER_STATUS_PENDING     TransferStatus = 1
	TransferStatus_TRANSFER_STATUS_POSTED      TransferStatus = 2
	TransferStatus_TRANSFER_STATUS_VOIDED      TransferStatus = 3
)

// Enum value maps for TransferStatus.
var (
	TransferStatus_name = map[int32]string{
		0: "TRANSFER_STATUS_UNSPECIFIED",
		1: "TRANSFER_STATUS_PENDING",
		2: "TRANSFER_STATUS_POSTED",
		3: "TRANSFER_STATUS_VOIDED",
	}
	TransferStatus_value = map[string]int32{
		"TRANSFER_STATUS_UNSPECIFIED": 0,
		"TRANSFER_STATUS_PENDING":     1,
		"TRANSFER_STATUS_POSTED":      2,
		"TRANSFER_STATUS_VOIDED":      3,
	}
)

func (x TransferStatus) Enum() *TransferStatus {
	p := new(TransferStatus)
	*p = x
	return p
}

func (x TransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ledger_proto_enumTypes[1].Descriptor()
}

func (TransferStatus) Type() protoreflect.EnumType {
	return &file_proto_ledger_proto_enumTypes[1]
}

func (x TransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatus.Descriptor instead.
func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{1}
}

// Account messages
type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`         // Unique account identifier (UUID or custom ID)
	LedgerId      uint32                 `protobuf:"varint,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`           // Ledger identifier (e.g., 1 for main ledger)
	Code          uint32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`                                   // Account code (chart of accounts)
	Type          AccountType            `protobuf:"varint,4,opt,name=type,proto3,enum=ledger.AccountType" json:"type,omitempty"`           // Account type
	UserData_128  string                 `protobuf:"bytes,5,opt,name=user_data_128,json=userData128,proto3" json:"user_data_128,omitempty"` // Custom metadata (128 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountRequest) GetLedgerId() uint32 {
	if x != nil {
		return x.LedgerId
	}
	return 0
}

func (x *CreateAccountRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAccountRequest) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *CreateAccountRequest) GetUserData_128() string {
	if x != nil {
		return x.UserData_128
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Account       *Account               `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAccountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Account       *Account               `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_proto_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAccountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountBalanceRequest) Reset() {
	*x = GetAccountBalanceRequest{}
	mi := &file_proto_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceRequest) ProtoMessage() {}

func (x *GetAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountBalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DebitsPosted   int64                  `protobuf:"varint,3,opt,name=debits_posted,json=debitsPosted,proto3" json:"debits_posted,omitempty"`
	CreditsPosted  int64                  `protobuf:"varint,4,opt,name=credits_posted,json=creditsPosted,proto3" json:"credits_posted,omitempty"`
	DebitsPending  int64                  `protobuf:"varint,5,opt,name=debits_pending,json=debitsPending,proto3" json:"debits_pending,omitempty"`
	CreditsPending int64                  `protobuf:"varint,6,opt,name=credits_pending,json=creditsPending,proto3" json:"credits_pending,omitempty"`
	Balance        int64                  `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"` // credits - debits
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAccountBalanceResponse) Reset() {
	*x = GetAccountBalanceResponse{}
	mi := &file_proto_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceResponse) ProtoMessage() {}

func (x *GetAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAccountBalanceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetAccountBalanceResponse) GetDebitsPosted() int64 {
	if x != nil {
		return x.DebitsPosted
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetCreditsPosted() int64 {
	if x != nil {
		return x.CreditsPosted
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetDebitsPending() int64 {
	if x != nil {
		return x.DebitsPending
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetCreditsPending() int64 {
	if x != nil {
		return x.CreditsPending
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type Account struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LedgerId       uint32                 `protobuf:"varint,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	Code           uint32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type           AccountType            `protobuf:"varint,4,opt,name=type,proto3,enum=ledger.AccountType" json:"type,omitempty"`
	DebitsPosted   int64                  `protobuf:"varint,5,opt,name=debits_posted,json=debitsPosted,proto3" json:"debits_posted,omitempty"`
	CreditsPosted  int64                  `protobuf:"varint,6,opt,name=credits_posted,json=creditsPosted,proto3" json:"credits_posted,omitempty"`
	DebitsPending  int64                  `protobuf:"varint,7,opt,name=debits_pending,json=debitsPending,proto3" json:"debits_pending,omitempty"`
	CreditsPending int64                  `protobuf:"varint,8,opt,name=credits_pending,json=creditsPending,proto3" json:"credits_pending,omitempty"`
	UserData_128   string                 `protobuf:"bytes,9,opt,name=user_data_128,json=userData128,proto3" json:"user_data_128,omitempty"`
	Timestamp      int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetLedgerId() uint32 {
	if x != nil {
		return x.LedgerId
	}
	return 0
}

func (x *Account) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetDebitsPosted() int64 {
	if x != nil {
		return x.DebitsPosted
	}
	return 0
}

func (x *Account) GetCreditsPosted() int64 {
	if x != nil {
		return x.CreditsPosted
	}
	return 0
}

func (x *Account) GetDebitsPending() int64 {
	if x != nil {
		return x.DebitsPending
	}
	return 0
}

func (x *Account) GetCreditsPending() int64 {
	if x != nil {
		return x.CreditsPending
	}
	return 0
}

func (x *Account) GetUserData_128() string {
	if x != nil {
		return x.UserData_128
	}
	return ""
}

func (x *Account) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Transfer messages
type CreateTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransferId      string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`                  // Unique transfer identifier
	DebitAccountId  string                 `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`    // Source account
	CreditAccountId string                 `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"` // Destination account
	Amount          int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                           // Amount in smallest currency unit (e.g., cents)
	LedgerId        uint32                 `protobuf:"varint,5,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`                       // Ledger identifier
	Code            uint32                 `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`                                               // Transfer code (reason/category)
	UserData_128    string                 `protobuf:"bytes,7,opt,name=user_data_128,json=userData128,proto3" json:"user_data_128,omitempty"`             // Custom metadata
	Timeout         int64                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`                                         // Timeout for pending transfers (nanoseconds)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_proto_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *CreateTransferRequest) GetDebitAccountId() string {
	if x != nil {
		return x.DebitAccountId
	}
	return ""
}

func (x *CreateTransferRequest) GetCreditAccountId() string {
	if x != nil {
		return x.CreditAccountId
	}
	return ""
}

func (x *CreateTransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransferRequest) GetLedgerId() uint32 {
	if x != nil {
		return x.LedgerId
	}
	return 0
}

func (x *CreateTransferRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTransferRequest) GetUserData_128() string {
	if x != nil {
		return x.UserData_128
	}
	return ""
}

func (x *CreateTransferRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Transfer      *Transfer              `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_proto_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_proto_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type GetTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Transfer      *Transfer              `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferResponse) Reset() {
	*x = GetTransferResponse{}
	mi := &file_proto_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferResponse) ProtoMessage() {}

func (x *GetTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferResponse.ProtoReflect.Descriptor instead.
func (*GetTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *GetTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type GetAccountTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                   // Maximum number of transfers to return
	TimestampMin  int64                  `protobuf:"varint,3,opt,name=timestamp_min,json=timestampMin,proto3" json:"timestamp_min,omitempty"` // Filter by minimum timestamp
	TimestampMax  int64                  `protobuf:"varint,4,opt,name=timestamp_max,json=timestampMax,proto3" json:"timestamp_max,omitempty"` // Filter by maximum timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTransfersRequest) Reset() {
	*x = GetAccountTransfersRequest{}
	mi := &file_proto_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransfersRequest) ProtoMessage() {}

func (x *GetAccountTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransfersRequest.ProtoReflect.Descriptor instead.
func (*GetAccountTransfersRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *GetAccountTransfersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountTransfersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAccountTransfersRequest) GetTimestampMin() int64 {
	if x != nil {
		return x.TimestampMin
	}
	return 0
}

func (x *GetAccountTransfersRequest) GetTimestampMax() int64 {
	if x != nil {
		return x.TimestampMax
	}
	return 0
}

type GetAccountTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Transfers     []*Transfer            `protobuf:"bytes,3,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTransfersResponse) Reset() {
	*x = GetAccountTransfersResponse{}
	mi := &file_proto_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransfersResponse) ProtoMessage() {}

func (x *GetAccountTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransfersResponse.ProtoReflect.Descriptor instead.
func (*GetAccountTransfersResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *GetAccountTransfersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAccountTransfersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetAccountTransfersResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type Transfer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransferId      string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	DebitAccountId  string                 `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId string                 `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	LedgerId        uint32                 `protobuf:"varint,5,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	Code            uint32                 `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	Status          TransferStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=ledger.TransferStatus" json:"status,omitempty"`
	UserData_128    string                 `protobuf:"bytes,8,opt,name=user_data_128,json=userData128,proto3" json:"user_data_128,omitempty"`
	Timestamp       int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_proto_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *Transfer) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *Transfer) GetDebitAccountId() string {
	if x != nil {
		return x.DebitAccountId
	}
	return ""
}

func (x *Transfer) GetCreditAccountId() string {
	if x != nil {
		return x.CreditAccountId
	}
	return ""
}

func (x *Transfer) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetLedgerId() uint32 {
	if x != nil {
		return x.LedgerId
	}
	return 0
}

func (x *Transfer) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Transfer) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_TRANSFER_STATUS_UNSPECIFIED
}

func (x *Transfer) GetUserData_128() string {
	if x != nil {
		return x.UserData_128
	}
	return ""
}

func (x *Transfer) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Two-phase commit messages
type CreatePendingTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransferId      string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	DebitAccountId  string                 `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId string                 `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	LedgerId        uint32                 `protobuf:"varint,5,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	Code            uint32                 `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	UserData_128    string                 `protobuf:"bytes,7,opt,name=user_data_128,json=userData128,proto3" json:"user_data_128,omitempty"`
	Timeout         int64                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"` // Timeout in nanoseconds (0 = no timeout)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePendingTransferRequest) Reset() {
	*x = CreatePendingTransferRequest{}
	mi := &file_proto_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePendingTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePendingTransferRequest) ProtoMessage() {}

func (x *CreatePendingTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePendingTransferRequest.ProtoReflect.Descriptor instead.
func (*CreatePendingTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePendingTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *CreatePendingTransferRequest) GetDebitAccountId() string {
	if x != nil {
		return x.DebitAccountId
	}
	return ""
}

func (x *CreatePendingTransferRequest) GetCreditAccountId() string {
	if x != nil {
		return x.CreditAccountId
	}
	return ""
}

func (x *CreatePendingTransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePendingTransferRequest) GetLedgerId() uint32 {
	if x != nil {
		return x.LedgerId
	}
	return 0
}

func (x *CreatePendingTransferRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreatePendingTransferRequest) GetUserData_128() string {
	if x != nil {
		return x.UserData_128
	}
	return ""
}

func (x *CreatePendingTransferRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type CreatePendingTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Transfer      *Transfer              `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePendingTransferResponse) Reset() {
	*x = CreatePendingTransferResponse{}
	mi := &file_proto_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePendingTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePendingTransferResponse) ProtoMessage() {}

func (x *CreatePendingTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePendingTransferResponse.ProtoReflect.Descriptor instead.
func (*CreatePendingTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePendingTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePendingTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreatePendingTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type PostPendingTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPendingTransferRequest) Reset() {
	*x = PostPendingTransferRequest{}
	mi := &file_proto_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPendingTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPendingTransferRequest) ProtoMessage() {}

func (x *PostPendingTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPendingTransferRequest.ProtoReflect.Descriptor instead.
func (*PostPendingTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *PostPendingTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type PostPendingTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPendingTransferResponse) Reset() {
	*x = PostPendingTransferResponse{}
	mi := &file_proto_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPendingTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPendingTransferResponse) ProtoMessage() {}

func (x *PostPendingTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPendingTransferResponse.ProtoReflect.Descriptor instead.
func (*PostPendingTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{17}
}

func (x *PostPendingTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PostPendingTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VoidPendingTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidPendingTransferRequest) Reset() {
	*x = VoidPendingTransferRequest{}
	mi := &file_proto_ledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidPendingTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidPendingTransferRequest) ProtoMessage() {}

func (x *VoidPendingTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidPendingTransferRequest.ProtoReflect.Descriptor instead.
func (*VoidPendingTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{18}
}

func (x *VoidPendingTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type VoidPendingTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidPendingTransferResponse) Reset() {
	*x = VoidPendingTransferResponse{}
	mi := &file_proto_ledger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidPendingTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidPendingTransferResponse) ProtoMessage() {}

func (x *VoidPendingTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidPendingTransferResponse.ProtoReflect.Descriptor instead.
func (*VoidPendingTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{19}
}

func (x *VoidPendingTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VoidPendingTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Reconciliation messages
type ReconcilePaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`                     // Mojaloop payment ID
	TransactionHash string                 `protobuf:"bytes,2,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`   // Blockchain transaction hash
	DebitAccountId  string                 `protobuf:"bytes,3,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`    // Payer account
	CreditAccountId string                 `protobuf:"bytes,4,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"` // Payee account
	Amount          int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Code            uint32                 `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`        // Transfer code
	Metadata        string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"` // Additional metadata (JSON)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReconcilePaymentRequest) Reset() {
	*x = ReconcilePaymentRequest{}
	mi := &file_proto_ledger_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilePaymentRequest) ProtoMessage() {}

func (x *ReconcilePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilePaymentRequest.ProtoReflect.Descriptor instead.
func (*ReconcilePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{20}
}

func (x *ReconcilePaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ReconcilePaymentRequest) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *ReconcilePaymentRequest) GetDebitAccountId() string {
	if x != nil {
		return x.DebitAccountId
	}
	return ""
}

func (x *ReconcilePaymentRequest) GetCreditAccountId() string {
	if x != nil {
		return x.CreditAccountId
	}
	return ""
}

func (x *ReconcilePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReconcilePaymentRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReconcilePaymentRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type ReconcilePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TransferId    string                 `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcilePaymentResponse) Reset() {
	*x = ReconcilePaymentResponse{}
	mi := &file_proto_ledger_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilePaymentResponse) ProtoMessage() {}

func (x *ReconcilePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilePaymentResponse.ProtoReflect.Descriptor instead.
func (*ReconcilePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{21}
}

func (x *ReconcilePaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReconcilePaymentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReconcilePaymentResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ReconcilePaymentResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetLedgerBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerId      uint32                 `protobuf:"varint,1,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerBalanceRequest) Reset() {
	*x = GetLedgerBalanceRequest{}
	mi := &file_proto_ledger_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerBalanceRequest) ProtoMessage() {}

func (x *GetLedgerBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{22}
}

func (x *GetLedgerBalanceRequest) GetLedgerId() uint32 {
	if x != nil {
		return x.LedgerId
	}
	return 0
}

type GetLedgerBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TotalDebits   int64                  `protobuf:"varint,3,opt,name=total_debits,json=totalDebits,proto3" json:"total_debits,omitempty"`
	TotalCredits  int64                  `protobuf:"varint,4,opt,name=total_credits,json=totalCredits,proto3" json:"total_credits,omitempty"`
	Balance       int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerBalanceResponse) Reset() {
	*x = GetLedgerBalanceResponse{}
	mi := &file_proto_ledger_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerBalanceResponse) ProtoMessage() {}

func (x *GetLedgerBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{23}
}

func (x *GetLedgerBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLedgerBalanceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetLedgerBalanceResponse) GetTotalDebits() int64 {
	if x != nil {
		return x.TotalDebits
	}
	return 0
}

func (x *GetLedgerBalanceResponse) GetTotalCredits() int64 {
	if x != nil {
		return x.TotalCredits
	}
	return 0
}

func (x *GetLedgerBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ledger.proto\x12\x06ledger\"\xb3\x01\n" +
	"\x14CreateAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\rR\bledgerId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.ledger.AccountTypeR\x04type\x12\"\n" +
	"\ruser_data_128\x18\x05 \x01(\tR\vuserData128\"r\n" +
	"\x15CreateAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\aaccount\x18\x03 \x01(\v2\x0f.ledger.AccountR\aaccount\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"o\n" +
	"\x12GetAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\aaccount\x18\x03 \x01(\v2\x0f.ledger.AccountR\aaccount\"9\n" +
	"\x18GetAccountBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x81\x02\n" +
	"\x19GetAccountBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rdebits_posted\x18\x03 \x01(\x03R\fdebitsPosted\x12%\n" +
	"\x0ecredits_posted\x18\x04 \x01(\x03R\rcreditsPosted\x12%\n" +
	"\x0edebits_pending\x18\x05 \x01(\x03R\rdebitsPending\x12'\n" +
	"\x0fcredits_pending\x18\x06 \x01(\x03R\x0ecreditsPending\x12\x18\n" +
	"\abalance\x18\a \x01(\x03R\abalance\"\xe0\x02\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\rR\bledgerId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.ledger.AccountTypeR\x04type\x12#\n" +
	"\rdebits_posted\x18\x05 \x01(\x03R\fdebitsPosted\x12%\n" +
	"\x0ecredits_posted\x18\x06 \x01(\x03R\rcreditsPosted\x12%\n" +
	"\x0edebits_pending\x18\a \x01(\x03R\rdebitsPending\x12'\n" +
	"\x0fcredits_pending\x18\b \x01(\x03R\x0ecreditsPending\x12\"\n" +
	"\ruser_data_128\x18\t \x01(\tR\vuserData128\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\"\x95\x02\n" +
	"\x15CreateTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\tR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\tR\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tledger_id\x18\x05 \x01(\rR\bledgerId\x12\x12\n" +
	"\x04code\x18\x06 \x01(\rR\x04code\x12\"\n" +
	"\ruser_data_128\x18\a \x01(\tR\vuserData128\x12\x18\n" +
	"\atimeout\x18\b \x01(\x03R\atimeout\"v\n" +
	"\x16CreateTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\btransfer\x18\x03 \x01(\v2\x10.ledger.TransferR\btransfer\"5\n" +
	"\x12GetTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"s\n" +
	"\x13GetTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\btransfer\x18\x03 \x01(\v2\x10.ledger.TransferR\btransfer\"\x9b\x01\n" +
	"\x1aGetAccountTransfersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12#\n" +
	"\rtimestamp_min\x18\x03 \x01(\x03R\ftimestampMin\x12#\n" +
	"\rtimestamp_max\x18\x04 \x01(\x03R\ftimestampMax\"}\n" +
	"\x1bGetAccountTransfersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\ttransfers\x18\x03 \x03(\v2\x10.ledger.TransferR\ttransfers\"\xbc\x02\n" +
	"\bTransfer\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\tR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\tR\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tledger_id\x18\x05 \x01(\rR\bledgerId\x12\x12\n" +
	"\x04code\x18\x06 \x01(\rR\x04code\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.ledger.TransferStatusR\x06status\x12\"\n" +
	"\ruser_data_128\x18\b \x01(\tR\vuserData128\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\x9c\x02\n" +
	"\x1cCreatePendingTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\tR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\tR\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tledger_id\x18\x05 \x01(\rR\bledgerId\x12\x12\n" +
	"\x04code\x18\x06 \x01(\rR\x04code\x12\"\n" +
	"\ruser_data_128\x18\a \x01(\tR\vuserData128\x12\x18\n" +
	"\atimeout\x18\b \x01(\x03R\atimeout\"}\n" +
	"\x1dCreatePendingTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\btransfer\x18\x03 \x01(\v2\x10.ledger.TransferR\btransfer\"=\n" +
	"\x1aPostPendingTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"M\n" +
	"\x1bPostPendingTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"=\n" +
	"\x1aVoidPendingTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"M\n" +
	"\x1bVoidPendingTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x81\x02\n" +
	"\x17ReconcilePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12)\n" +
	"\x10transaction_hash\x18\x02 \x01(\tR\x0ftransactionHash\x12(\n" +
	"\x10debit_account_id\x18\x03 \x01(\tR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x04 \x01(\tR\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04code\x18\x06 \x01(\rR\x04code\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"\x89\x01\n" +
	"\x18ReconcilePaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vtransfer_id\x18\x03 \x01(\tR\n" +
	"transferId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"6\n" +
	"\x17GetLedgerBalanceRequest\x12\x1b\n" +
	"\tledger_id\x18\x01 \x01(\rR\bledgerId\"\xac\x01\n" +
	"\x18GetLedgerBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\ftotal_debits\x18\x03 \x01(\x03R\vtotalDebits\x12#\n" +
	"\rtotal_credits\x18\x04 \x01(\x03R\ftotalCredits\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x03R\abalance*\xac\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACCOUNT_TYPE_ASSET\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_TYPE_LIABILITY\x10\x02\x12\x17\n" +
	"\x13ACCOUNT_TYPE_EQUITY\x10\x03\x12\x18\n" +
	"\x14ACCOUNT_TYPE_REVENUE\x10\x04\x12\x18\n" +
	"\x14ACCOUNT_TYPE_EXPENSE\x10\x05*\x86\x01\n" +
	"\x0eTransferStatus\x12\x1f\n" +
	"\x1bTRANSFER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRANSFER_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16TRANSFER_STATUS_POSTED\x10\x02\x12\x1a\n" +
	"\x16TRANSFER_STATUS_VOIDED\x10\x032\xc9\a\n" +
	"\rLedgerService\x12L\n" +
	"\rCreateAccount\x12\x1c.ledger.CreateAccountRequest\x1a\x1d.ledger.CreateAccountResponse\x12C\n" +
	"\n" +
	"GetAccount\x12\x19.ledger.GetAccountRequest\x1a\x1a.ledger.GetAccountResponse\x12X\n" +
	"\x11GetAccountBalance\x12 .ledger.GetAccountBalanceRequest\x1a!.ledger.GetAccountBalanceResponse\x12O\n" +
	"\x0eCreateTransfer\x12\x1d.ledger.CreateTransferRequest\x1a\x1e.ledger.CreateTransferResponse\x12F\n" +
	"\vGetTransfer\x12\x1a.ledger.GetTransferRequest\x1a\x1b.ledger.GetTransferResponse\x12^\n" +
	"\x13GetAccountTransfers\x12\".ledger.GetAccountTransfersRequest\x1a#.ledger.GetAccountTransfersResponse\x12d\n" +
	"\x15CreatePendingTransfer\x12$.ledger.CreatePendingTransferRequest\x1a%.ledger.CreatePendingTransferResponse\x12^\n" +
	"\x13PostPendingTransfer\x12\".ledger.PostPendingTransferRequest\x1a#.ledger.PostPendingTransferResponse\x12^\n" +
	"\x13VoidPendingTransfer\x12\".ledger.VoidPendingTransferRequest\x1a#.ledger.VoidPendingTransferResponse\x12U\n" +
	"\x10ReconcilePayment\x12\x1f.ledger.ReconcilePaymentRequest\x1a .ledger.ReconcilePaymentResponse\x12U\n" +
	"\x10GetLedgerBalance\x12\x1f.ledger.GetLedgerBalanceRequest\x1a .ledger.GetLedgerBalanceResponseB/Z-github.com/idlr-pts/tigerbeetle-service/protob\x06proto3"

var (
	file_proto_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_proto_rawDescData []byte
)

func file_proto_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_proto_rawDescData
}

var file_proto_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_ledger_proto_goTypes = []any{
	(AccountType)(0),                      // 0: ledger.AccountType
	(TransferStatus)(0),                   // 1: ledger.TransferStatus
	(*CreateAccountRequest)(nil),          // 2: ledger.CreateAccountRequest
	(*CreateAccountResponse)(nil),         // 3: ledger.CreateAccountResponse
	(*GetAccountRequest)(nil),             // 4: ledger.GetAccountRequest
	(*GetAccountResponse)(nil),            // 5: ledger.GetAccountResponse
	(*GetAccountBalanceRequest)(nil),      // 6: ledger.GetAccountBalanceRequest
	(*GetAccountBalanceResponse)(nil),     // 7: ledger.GetAccountBalanceResponse
	(*Account)(nil),                       // 8: ledger.Account
	(*CreateTransferRequest)(nil),         // 9: ledger.CreateTransferRequest
	(*CreateTransferResponse)(nil),        // 10: ledger.CreateTransferResponse
	(*GetTransferRequest)(nil),            // 11: ledger.GetTransferRequest
	(*GetTransferResponse)(nil),           // 12: ledger.GetTransferResponse
	(*GetAccountTransfersRequest)(nil),    // 13: ledger.GetAccountTransfersRequest
	(*GetAccountTransfersResponse)(nil),   // 14: ledger.GetAccountTransfersResponse
	(*Transfer)(nil),                      // 15: ledger.Transfer
	(*CreatePendingTransferRequest)(nil),  // 16: ledger.CreatePendingTransferRequest
	(*CreatePendingTransferResponse)(nil), // 17: ledger.CreatePendingTransferResponse
	(*PostPendingTransferRequest)(nil),    // 18: ledger.PostPendingTransferRequest
	(*PostPendingTransferResponse)(nil),   // 19: ledger.PostPendingTransferResponse
	(*VoidPendingTransferRequest)(nil),    // 20: ledger.VoidPendingTransferRequest
	(*VoidPendingTransferResponse)(nil),   // 21: ledger.VoidPendingTransferResponse
	(*ReconcilePaymentRequest)(nil),       // 22: ledger.ReconcilePaymentRequest
	(*ReconcilePaymentResponse)(nil),      // 23: ledger.ReconcilePaymentResponse
	(*GetLedgerBalanceRequest)(nil),       // 24: ledger.GetLedgerBalanceRequest
	(*GetLedgerBalanceResponse)(nil),      // 25: ledger.GetLedgerBalanceResponse
}
var file_proto_ledger_proto_depIdxs = []int32{
	0,  // 0: ledger.CreateAccountRequest.type:type_name -> ledger.AccountType
	8,  // 1: ledger.CreateAccountResponse.account:type_name -> ledger.Account
	8,  // 2: ledger.GetAccountResponse.account:type_name -> ledger.Account
	0,  // 3: ledger.Account.type:type_name -> ledger.AccountType
	15, // 4: ledger.CreateTransferResponse.transfer:type_name -> ledger.Transfer
	15, // 5: ledger.GetTransferResponse.transfer:type_name -> ledger.Transfer
	15, // 6: ledger.GetAccountTransfersResponse.transfers:type_name -> ledger.Transfer
	1,  // 7: ledger.Transfer.status:type_name -> ledger.TransferStatus
	15, // 8: ledger.CreatePendingTransferResponse.transfer:type_name -> ledger.Transfer
	2,  // 9: ledger.LedgerService.CreateAccount:input_type -> ledger.CreateAccountRequest
	4,  // 10: ledger.LedgerService.GetAccount:input_type -> ledger.GetAccountRequest
	6,  // 11: ledger.LedgerService.GetAccountBalance:input_type -> ledger.GetAccountBalanceRequest
	9,  // 12: ledger.LedgerService.CreateTransfer:input_type -> ledger.CreateTransferRequest
	11, // 13: ledger.LedgerService.GetTransfer:input_type -> ledger.GetTransferRequest
	13, // 14: ledger.LedgerService.GetAccountTransfers:input_type -> ledger.GetAccountTransfersRequest
	16, // 15: ledger.LedgerService.CreatePendingTransfer:input_type -> ledger.CreatePendingTransferRequest
	18, // 16: ledger.LedgerService.PostPendingTransfer:input_type -> ledger.PostPendingTransferRequest
	20, // 17: ledger.LedgerService.VoidPendingTransfer:input_type -> ledger.VoidPendingTransferRequest
	22, // 18: ledger.LedgerService.ReconcilePayment:input_type -> ledger.ReconcilePaymentRequest
	24, // 19: ledger.LedgerService.GetLedgerBalance:input_type -> ledger.GetLedgerBalanceRequest
	3,  // 20: ledger.LedgerService.CreateAccount:output_type -> ledger.CreateAccountResponse
	5,  // 21: ledger.LedgerService.GetAccount:output_type -> ledger.GetAccountResponse
	7,  // 22: ledger.LedgerService.GetAccountBalance:output_type -> ledger.GetAccountBalanceResponse
	10, // 23: ledger.LedgerService.CreateTransfer:output_type -> ledger.CreateTransferResponse
	12, // 24: ledger.LedgerService.GetTransfer:output_type -> ledger.GetTransferResponse
	14, // 25: ledger.LedgerService.GetAccountTransfers:output_type -> ledger.GetAccountTransfersResponse
	17, // 26: ledger.LedgerService.CreatePendingTransfer:output_type -> ledger.CreatePendingTransferResponse
	19, // 27: ledger.LedgerService.PostPendingTransfer:output_type -> ledger.PostPendingTransferResponse
	21, // 28: ledger.LedgerService.VoidPendingTransfer:output_type -> ledger.VoidPendingTransferResponse
	23, // 29: ledger.LedgerService.ReconcilePayment:output_type -> ledger.ReconcilePaymentResponse
	25, // 30: ledger.LedgerService.GetLedgerBalance:output_type -> ledger.GetLedgerBalanceResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_ledger_proto_init() }
func file_proto_ledger_proto_init() {
	if File_proto_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_proto_depIdxs,
		EnumInfos:         file_proto_ledger_proto_enumTypes,
		MessageInfos:      file_proto_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_proto = out.File
	file_proto_ledger_proto_goTypes = nil
	file_proto_ledger_proto_depIdxs = nil
}
