import { and, desc, eq, inArray } from "drizzle-orm";
import { commercialAccountMembers, commercialAccounts, commercialProducts, commercialSubscriptions, commercialUsageEvents, rowAccessAgreements, rowCorridors, rowEvents, rowFieldConfirmations, rowParcelFindings } from "../drizzle/schema";
import { requireDb } from "./db";

const PRODUCT_KEY = "right-of-way-manager";
const ACTIVE = ["trialing", "active", "past_due"] as const;
const AGREEMENT_TRANSITIONS: Record<string, string[]> = { draft: ["proposed"], proposed: ["under_review", "terminated"], under_review: ["executed", "terminated"], executed: ["expired", "terminated"], expired: [], terminated: [] };
type Role = "owner" | "billing_admin" | "row_manager" | "row_officer" | "row_reviewer";
const key = (prefix: string) => `${prefix}-${crypto.randomUUID().replace(/-/g, "").slice(0, 20).toUpperCase()}`;

function coordinatesValid(value: unknown): boolean {
  if (!Array.isArray(value)) return false;
  if (value.length >= 2 && typeof value[0] === "number" && typeof value[1] === "number") return Number.isFinite(value[0]) && Number.isFinite(value[1]) && value[0] >= -180 && value[0] <= 180 && value[1] >= -90 && value[1] <= 90;
  return value.length > 0 && value.every(coordinatesValid);
}
function validateGeometry(geometry: unknown) {
  if (!geometry || typeof geometry !== "object") throw new Error("A GeoJSON corridor geometry is required");
  const item = geometry as { type?: string; coordinates?: unknown };
  if (!(["LineString", "MultiLineString", "Polygon", "MultiPolygon"] as string[]).includes(item.type ?? "") || !coordinatesValid(item.coordinates)) throw new Error("Corridor geometry must be bounded WGS84 GeoJSON line or polygon coordinates");
}
async function membership(actorId: number, accountKey: string, roles: Role[]) {
  const db = await requireDb();
  const [row] = await db.select({ account: commercialAccounts, member: commercialAccountMembers }).from(commercialAccounts).innerJoin(commercialAccountMembers, eq(commercialAccountMembers.accountId, commercialAccounts.id)).where(and(eq(commercialAccounts.accountKey, accountKey), eq(commercialAccountMembers.userId, actorId))).limit(1);
  if (!row || !roles.includes(row.member.role as Role)) throw new Error("You do not have the required Right-of-Way role");
  const [entitlement] = await db.select().from(commercialSubscriptions).innerJoin(commercialProducts, eq(commercialProducts.id, commercialSubscriptions.productId)).where(and(eq(commercialSubscriptions.accountId, row.account.id), eq(commercialProducts.productKey, PRODUCT_KEY), inArray(commercialSubscriptions.status, [...ACTIVE]))).orderBy(desc(commercialSubscriptions.currentPeriodEnd)).limit(1);
  if (!entitlement) throw new Error("Right-of-Way Manager requires an active commercial entitlement");
  return { db, ...row };
}
async function usage(accountId: number, metricKey: string, sourceKey: string, metadata: Record<string, unknown>) { const db = await requireDb(); await db.insert(commercialUsageEvents).values({ accountId, metricKey, quantity: 1, idempotencyKey: `row:${metricKey}:${sourceKey}`, sourceType: "right_of_way", sourceKey, metadata }); }
export async function createRowAccount(input: { actorId: number; legalName: string; billingEmail: string }) {
  if (input.legalName.trim().length < 2 || !/^\S+@\S+\.\S+$/.test(input.billingEmail.trim())) throw new Error("A legal account name and valid billing email are required");
  const db = await requireDb(); const [product] = await db.select().from(commercialProducts).where(eq(commercialProducts.productKey, PRODUCT_KEY)).limit(1); if (!product?.active) throw new Error("Right-of-Way Manager is unavailable");
  const now = new Date(); const trialEnd = new Date(now.getTime() + 14 * 86_400_000);
  return db.transaction(async (tx) => { const [account] = await tx.insert(commercialAccounts).values({ accountKey: key("ROW"), legalName: input.legalName.trim(), billingEmail: input.billingEmail.trim().toLowerCase(), status: "trial", createdBy: input.actorId, createdAt: now, updatedAt: now }).returning(); await tx.insert(commercialAccountMembers).values({ accountId: account.id, userId: input.actorId, role: "owner", createdAt: now }); await tx.insert(commercialSubscriptions).values({ subscriptionKey: key("SUB"), accountId: account.id, productId: product.id, status: "trialing", startedAt: now, currentPeriodStart: now, currentPeriodEnd: trialEnd, createdAt: now, updatedAt: now }); return account; });
}
export async function createCorridor(input: { actorId: number; accountKey: string; name: string; purpose: string; geometryGeojson: unknown }) { const access = await membership(input.actorId, input.accountKey, ["owner", "row_manager"]); validateGeometry(input.geometryGeojson); if (input.name.trim().length < 2 || input.purpose.trim().length < 2) throw new Error("A bounded corridor name and purpose are required"); const [corridor] = await access.db.insert(rowCorridors).values({ accountId: access.account.id, corridorKey: key("COR"), name: input.name.trim(), purpose: input.purpose.trim(), geometryGeojson: input.geometryGeojson, createdBy: input.actorId, createdAt: new Date(), updatedAt: new Date() }).returning(); await access.db.insert(rowEvents).values({ accountId: access.account.id, entityType: "corridor", entityKey: corridor.corridorKey, eventType: "corridor_created", actorId: input.actorId, description: "Corridor recorded for operational analysis; no property right was determined.", metadata: {} }); return corridor; }
export async function createParcelFinding(input: { actorId: number; accountKey: string; corridorKey: string; parcelId: number; overlapMethod: string; overlapSummary: string; sourceReference: string }) { const access = await membership(input.actorId, input.accountKey, ["owner", "row_manager", "row_officer"]); if (!input.overlapMethod.trim() || input.overlapSummary.trim().length < 8 || !input.sourceReference.trim()) throw new Error("Method, factual overlap summary, and source reference are required"); const [corridor] = await access.db.select().from(rowCorridors).where(and(eq(rowCorridors.accountId, access.account.id), eq(rowCorridors.corridorKey, input.corridorKey))).limit(1); if (!corridor) throw new Error("Corridor was not found"); const [finding] = await access.db.insert(rowParcelFindings).values({ findingKey: key("RFD"), accountId: access.account.id, corridorId: corridor.id, parcelId: input.parcelId, status: "identified", overlapMethod: input.overlapMethod.trim(), overlapSummary: input.overlapSummary.trim(), sourceReference: input.sourceReference.trim(), createdAt: new Date(), updatedAt: new Date() }).returning(); await access.db.insert(rowEvents).values({ accountId: access.account.id, entityType: "finding", entityKey: finding.findingKey, eventType: "finding_recorded", actorId: input.actorId, description: "Parcel finding recorded pending independent verification.", metadata: { corridorKey: input.corridorKey } }); await usage(access.account.id, "monthly_row_findings", finding.findingKey, { corridorKey: input.corridorKey }); return finding; }
export async function reviewParcelFinding(input: { actorId: number; accountKey: string; findingKey: string; nextStatus: "verified" | "resolved" | "dismissed" }) { const access = await membership(input.actorId, input.accountKey, ["owner", "row_manager", "row_reviewer"]); const [finding] = await access.db.select().from(rowParcelFindings).where(and(eq(rowParcelFindings.accountId, access.account.id), eq(rowParcelFindings.findingKey, input.findingKey))).limit(1); if (!finding || !["identified", "verified"].includes(finding.status)) throw new Error("Finding cannot be reviewed in its current state"); const [updated] = await access.db.update(rowParcelFindings).set({ status: input.nextStatus, reviewedBy: input.actorId, reviewedAt: new Date(), updatedAt: new Date() }).where(eq(rowParcelFindings.id, finding.id)).returning(); await access.db.insert(rowEvents).values({ accountId: access.account.id, entityType: "finding", entityKey: updated.findingKey, eventType: "finding_reviewed", actorId: input.actorId, description: `Finding marked ${input.nextStatus}; this is not an ownership or acquisition decision.`, metadata: {} }); return updated; }
export async function createAccessAgreement(input: { actorId: number; accountKey: string; findingKey: string; agreementReference: string; termsReference: string; effectiveOn?: string; expiresOn?: string }) { const access = await membership(input.actorId, input.accountKey, ["owner", "row_manager"]); const [finding] = await access.db.select().from(rowParcelFindings).where(and(eq(rowParcelFindings.accountId, access.account.id), eq(rowParcelFindings.findingKey, input.findingKey))).limit(1); if (!finding || finding.status !== "verified") throw new Error("A verified finding is required before an agreement can be recorded"); if (!input.agreementReference.trim() || !input.termsReference.trim()) throw new Error("Agreement and terms references are required"); const [agreement] = await access.db.insert(rowAccessAgreements).values({ agreementKey: key("RAG"), accountId: access.account.id, findingId: finding.id, status: "draft", agreementReference: input.agreementReference.trim(), termsReference: input.termsReference.trim(), effectiveOn: input.effectiveOn ?? null, expiresOn: input.expiresOn ?? null, createdBy: input.actorId, createdAt: new Date(), updatedAt: new Date() }).returning(); await access.db.insert(rowEvents).values({ accountId: access.account.id, entityType: "agreement", entityKey: agreement.agreementKey, eventType: "agreement_recorded", actorId: input.actorId, description: "Agreement record opened pending governed review and execution.", metadata: { findingKey: input.findingKey } }); return agreement; }
export async function transitionAccessAgreement(input: { actorId: number; accountKey: string; agreementKey: string; nextStatus: "proposed" | "under_review" | "executed" | "expired" | "terminated" }) { const access = await membership(input.actorId, input.accountKey, ["owner", "row_manager", "row_reviewer"]); const [agreement] = await access.db.select().from(rowAccessAgreements).where(and(eq(rowAccessAgreements.accountId, access.account.id), eq(rowAccessAgreements.agreementKey, input.agreementKey))).limit(1); if (!agreement || !AGREEMENT_TRANSITIONS[agreement.status].includes(input.nextStatus)) throw new Error("Agreement transition is not allowed"); const now = new Date(); const [updated] = await access.db.update(rowAccessAgreements).set({ status: input.nextStatus, approvedBy: input.nextStatus === "executed" ? input.actorId : agreement.approvedBy, approvedAt: input.nextStatus === "executed" ? now : agreement.approvedAt, updatedAt: now }).where(eq(rowAccessAgreements.id, agreement.id)).returning(); await access.db.insert(rowEvents).values({ accountId: access.account.id, entityType: "agreement", entityKey: updated.agreementKey, eventType: "agreement_transition", actorId: input.actorId, description: `Agreement moved to ${input.nextStatus}; external legal execution remains required.`, metadata: {} }); return updated; }
export async function captureRowFieldConfirmation(input: { actorId: number; accountKey: string; findingKey: string; latitude: number; longitude: number; observedAt: string; evidenceReference: string; note: string }) { const access = await membership(input.actorId, input.accountKey, ["owner", "row_manager", "row_officer"]); if (!Number.isFinite(input.latitude) || input.latitude < -90 || input.latitude > 90 || !Number.isFinite(input.longitude) || input.longitude < -180 || input.longitude > 180 || input.note.trim().length < 3 || !input.evidenceReference.trim()) throw new Error("Valid field coordinates, evidence reference, and note are required"); const observedAt = new Date(input.observedAt); if (Number.isNaN(observedAt.getTime()) || observedAt.getTime() > Date.now() + 300_000) throw new Error("Observation time must be valid and not in the future"); const [finding] = await access.db.select().from(rowParcelFindings).where(and(eq(rowParcelFindings.accountId, access.account.id), eq(rowParcelFindings.findingKey, input.findingKey))).limit(1); if (!finding) throw new Error("Finding was not found"); const [confirmation] = await access.db.insert(rowFieldConfirmations).values({ confirmationKey: key("RFC"), accountId: access.account.id, findingId: finding.id, latitude: input.latitude, longitude: input.longitude, observedAt, evidenceReference: input.evidenceReference.trim(), note: input.note.trim(), capturedBy: input.actorId, createdAt: new Date() }).returning(); await access.db.insert(rowEvents).values({ accountId: access.account.id, entityType: "field_confirmation", entityKey: confirmation.confirmationKey, eventType: "field_confirmation_captured", actorId: input.actorId, description: "Field confirmation captured for reviewer assessment.", metadata: { findingKey: input.findingKey } }); return confirmation; }
export async function getRightOfWayDashboard(input: { actorId: number; accountKey: string }) { const access = await membership(input.actorId, input.accountKey, ["owner", "billing_admin", "row_manager", "row_officer", "row_reviewer"]); const corridors = await access.db.select().from(rowCorridors).where(eq(rowCorridors.accountId, access.account.id)).orderBy(desc(rowCorridors.updatedAt)); const findings = await access.db.select().from(rowParcelFindings).where(eq(rowParcelFindings.accountId, access.account.id)).orderBy(desc(rowParcelFindings.updatedAt)); const agreements = await access.db.select().from(rowAccessAgreements).where(eq(rowAccessAgreements.accountId, access.account.id)).orderBy(desc(rowAccessAgreements.updatedAt)); const confirmations = await access.db.select().from(rowFieldConfirmations).where(eq(rowFieldConfirmations.accountId, access.account.id)).orderBy(desc(rowFieldConfirmations.observedAt)); return { account: access.account, role: access.member.role, corridors, findings, agreements, confirmations, metrics: { activeCorridors: corridors.length, openFindings: findings.filter((item) => ["identified", "verified"].includes(item.status)).length, executedAgreements: agreements.filter((item) => item.status === "executed").length, unreviewedFieldConfirmations: confirmations.filter((item) => !item.reviewedAt).length } }; }
