apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: idlr-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: consumerGroup
      value: "idlr-pts-dapr"
    - name: clientID
      value: "idlr-pts"
    - name: authRequired
      value: "false"
    - name: initialOffset
      value: "newest"
    - name: maxMessageBytes
      value: "1048576"
