apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: idlr-statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis:6379"
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
    - name: keyPrefix
      value: "idlr-pts"
    - name: ttlInSeconds
      value: "3600"
