import { z } from "zod";
import { protectedProcedure, router } from "../../_core/trpc";
import * as s from "../../portfolioProductsService";
const accountKey=z.string().regex(/^(ACQ|EXP|API|PLN|RUR|SVC)-[A-Z0-9]{20}$/); const product=z.enum(["acquisition-intelligence","resilience-exposure-monitor","property-data-api","planning-analytics","rural-agribusiness-hub","trusted-service-directory"]);
export const portfolioProductsRouter=router({
 createAccount:protectedProcedure.input(z.object({productKey:product,legalName:z.string().trim().min(2).max(255),billingEmail:z.string().email().max(320)})).mutation(({ctx,input})=>s.createPortfolioAccount({actorId:ctx.user.id,...input})),
 acquisitionDashboard:protectedProcedure.input(z.object({accountKey:z.string().regex(/^ACQ-[A-Z0-9]{20}$/)})).query(({ctx,input})=>s.acquisitionDashboard({actorId:ctx.user.id,...input})), createDataroom:protectedProcedure.input(z.object({accountKey:z.string().regex(/^ACQ-[A-Z0-9]{20}$/),name:z.string().trim().min(2).max(200),purpose:z.string().trim().min(2).max(160)})).mutation(({ctx,input})=>s.createDataroom({actorId:ctx.user.id,...input})), addDiligenceItem:protectedProcedure.input(z.object({accountKey:z.string().regex(/^ACQ-[A-Z0-9]{20}$/),dataroomKey:z.string().regex(/^DDR-[A-Z0-9]{20}$/),parcelId:z.number().int().positive().optional(),category:z.string().trim().min(2).max(64),sourceReference:z.string().trim().min(2).max(160),factualSummary:z.string().trim().min(8).max(4000)})).mutation(({ctx,input})=>s.addDiligenceItem({actorId:ctx.user.id,...input})),
 exposureDashboard:protectedProcedure.input(z.object({accountKey:z.string().regex(/^EXP-[A-Z0-9]{20}$/)})).query(({ctx,input})=>s.exposureDashboard({actorId:ctx.user.id,...input})), createExposurePortfolio:protectedProcedure.input(z.object({accountKey:z.string().regex(/^EXP-[A-Z0-9]{20}$/),name:z.string().trim().min(2).max(200)})).mutation(({ctx,input})=>s.createExposurePortfolio({actorId:ctx.user.id,...input})), addExposureAsset:protectedProcedure.input(z.object({accountKey:z.string().regex(/^EXP-[A-Z0-9]{20}$/),portfolioKey:z.string().regex(/^EPO-[A-Z0-9]{20}$/),label:z.string().trim().min(2).max(200),parcelId:z.number().int().positive().optional(),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180)})).mutation(({ctx,input})=>s.addExposureAsset({actorId:ctx.user.id,...input})), addExposureSnapshot:protectedProcedure.input(z.object({accountKey:z.string().regex(/^EXP-[A-Z0-9]{20}$/),portfolioKey:z.string().regex(/^EPO-[A-Z0-9]{20}$/),contextLayer:z.string().trim().min(2).max(64),sourceReference:z.string().trim().min(2).max(160),observedAt:z.string().datetime(),summary:z.string().trim().min(8).max(4000),humanReviewNote:z.string().trim().max(4000).optional()})).mutation(({ctx,input})=>s.addExposureSnapshot({actorId:ctx.user.id,...input})),
 createApiClient:protectedProcedure.input(z.object({accountKey:z.string().regex(/^API-[A-Z0-9]{20}$/),name:z.string().trim().min(2).max(160),purpose:z.string().trim().min(8).max(400),scopes:z.array(z.string().trim().regex(/^[a-z][a-z0-9_.:-]{1,95}$/)).min(1).max(20)})).mutation(({ctx,input})=>s.createApiClient({actorId:ctx.user.id,...input})), recordApiUsage:protectedProcedure.input(z.object({clientSecret:z.string().min(20).max(128),endpoint:z.string().regex(/^\/v1\//).max(160),scope:z.string().trim().min(2).max(96),responseCount:z.number().int().min(0),purposeReference:z.string().trim().min(2).max(160)})).mutation(({input})=>s.recordApiUsage(input)),
 createPlanningReport:protectedProcedure.input(z.object({accountKey:z.string().regex(/^PLN-[A-Z0-9]{20}$/),name:z.string().trim().min(2).max(200),cohortSize:z.number().int().min(0),minimumCohort:z.number().int().min(5).max(1000000),summary:z.record(z.string(),z.unknown())})).mutation(({ctx,input})=>s.createPlanningReport({actorId:ctx.user.id,...input})),
 createRuralCase:protectedProcedure.input(z.object({accountKey:z.string().regex(/^RUR-[A-Z0-9]{20}$/),parcelId:z.number().int().positive().optional(),programType:z.string().trim().min(2).max(96),consentReference:z.string().trim().min(2).max(160),serviceReference:z.string().trim().min(2).max(160)})).mutation(({ctx,input})=>s.createRuralCase({actorId:ctx.user.id,...input})),
 createProvider:protectedProcedure.input(z.object({accountKey:z.string().regex(/^SVC-[A-Z0-9]{20}$/),legalName:z.string().trim().min(2).max(255),serviceCategories:z.array(z.string().trim().min(2).max(96)).min(1).max(20),serviceRadiusKm:z.number().int().min(1).max(1000)})).mutation(({ctx,input})=>s.createProvider({actorId:ctx.user.id,...input})), reviewProvider:protectedProcedure.input(z.object({accountKey:z.string().regex(/^SVC-[A-Z0-9]{20}$/),providerKey:z.string().regex(/^PRV-[A-Z0-9]{20}$/),nextStatus:z.enum(["verified","rejected","suspended"]),verificationReference:z.string().trim().min(2).max(160)})).mutation(({ctx,input})=>s.reviewProvider({actorId:ctx.user.id,...input})), createServiceRequest:protectedProcedure.input(z.object({accountKey:z.string().regex(/^SVC-[A-Z0-9]{20}$/),providerKey:z.string().regex(/^PRV-[A-Z0-9]{20}$/).optional(),parcelId:z.number().int().positive().optional(),serviceCategory:z.string().trim().min(2).max(96),consentReference:z.string().trim().min(2).max(160),requesterReference:z.string().trim().min(2).max(160)})).mutation(({ctx,input})=>s.createServiceRequest({actorId:ctx.user.id,...input})), fileServiceDispute:protectedProcedure.input(z.object({accountKey:z.string().regex(/^SVC-[A-Z0-9]{20}$/),requestKey:z.string().regex(/^SRQ-[A-Z0-9]{20}$/),grounds:z.string().trim().min(10).max(4000)})).mutation(({ctx,input})=>s.fileServiceDispute({actorId:ctx.user.id,...input})),
 genericDashboard:protectedProcedure.input(z.object({accountKey,product})).query(({ctx,input})=>s.genericPortfolioDashboard({actorId:ctx.user.id,...input})),
});
